[project]
name = "lora-api" 
version = "0.0.1" 
description = "" 
authors = [ 
   {name = "sebalooc-35",email = "andres.rodriguez.pama@gmail.com"},
   {name = "vallit0",email = "vallit0@gmail.com"} 
] 
readme = "README.md" 
requires-python = ">=3.12" 
dependencies = [ 
   "gunicorn (>=23.0.0,<24.0.0)", 
   "uvicorn (>=0.38.0,<0.39.0)", 
   "fastapi (>=0.119.1,<0.120.0)" 
] 

[build-system] 
requires = ["poetry-core>=2.0.0,<3.0.0"] 
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=8.4.2,<9.0.0)"
]
